apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v8ox88eox-nodejs 
  janus-idp.io/tekton: v8ox88eox-nodejs
  backstage.io/kubernetes-id: v8ox88eox-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v8ox88eox-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml